baseURL = "https://www.audido.com/allie/"
languageCode = "en-us"
title = "Allison Shertzer"
theme = "notrack"

[params]
  author = "Allison Shertzer"

  [params.social]
    email = "shertzer@pitt.edu"
    googlescholar = "user=eMHe2JQAAAAJ"
    twitter = "econhist_allday"
